server:
    port: 8080

spring:
    application:
        name: prproiectoiect
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        properties:
            hibernate:
                default_schema: proiect
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show-sql: true
                ddl-auto: none
        open-in-view: false
    flyway:
        baseline-on-migrate: true
        enabled: true
        validate-on-migrate: false
        table: proiect_schema_version
        baseline-version: 0
